id: IFADE284F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:44:32+00:00'
last_modified: '2022-06-07T13:39:34.398081+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25113
  title: ནག་བཟའ་སྡེ་བ་དང་ཤ་བྲང་དགོན་པའི་ལོ་རྒྱུས་ཕྱི་རབས་གཞོན་ནུའི་རྣ་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1354':
      image_group_id: I1GS53205
      title: ''
      total_pages: 87
      order: 1
      base_file: 1354.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
