id: P000762
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W25113
  title: ནག་བཟའ་སྡེ་བ་དང་ཤ་བྲང་དགོན་པའི་ལོ་རྒྱུས་ཕྱི་རབས་གཞོན་ནུའི་རྣ་རྒྱན
  author: ''
  volumes:
    c9cf42a96a49461e8607ae8acc3f1483:
      image_group_id: I1GS53205
      title: ''
      volume_number: 1
      total_pages: 87
      base_file: v001.txt
